services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: tfm_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: tfm_movies
      POSTGRES_USER: tfm_user
      POSTGRES_PASSWORD: tfm_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: